<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('productos')->insert([
            [
                'categoria_id' => 1,
                'laboratorio_id' => 1,
                'codigo_producto' => 'PROD001',
                'codigo_barra' => '123456789001',
                'nombre_comercial' => 'Paracetamol 500mg',
                'nombre_generico' => 'Paracetamol',
                'forma_farmaceutica' => 'Tableta',
                'presentacion' => 'Caja x 20',
                'concentracion' => '500mg',
                'accion_terapeutica' => 'Analgésico',
                'unidad_medida' => 'mg',
                'usa_receta' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categoria_id' => 2,
                'laboratorio_id' => 2,
                'codigo_producto' => 'PROD002',
                'codigo_barra' => '123456789002',
                'nombre_comercial' => 'Ibuprofeno 400mg',
                'nombre_generico' => 'Ibuprofeno',
                'forma_farmaceutica' => 'Tableta',
                'presentacion' => 'Caja x 30',
                'concentracion' => '400mg',
                'accion_terapeutica' => 'Antiinflamatorio',
                'unidad_medida' => 'mg',
                'usa_receta' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categoria_id' => 1,
                'laboratorio_id' => 1,
                'codigo_producto' => 'PROD003',
                'codigo_barra' => '123456789003',
                'nombre_comercial' => 'Amoxicilina 500mg',
                'nombre_generico' => 'Amoxicilina',
                'forma_farmaceutica' => 'Cápsula',
                'presentacion' => 'Caja x 24',
                'concentracion' => '500mg',
                'accion_terapeutica' => 'Antibiótico',
                'unidad_medida' => 'mg',
                'usa_receta' => true,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categoria_id' => 3,
                'laboratorio_id' => 3,
                'codigo_producto' => 'PROD004',
                'codigo_barra' => '123456789004',
                'nombre_comercial' => 'Loratadina 10mg',
                'nombre_generico' => 'Loratadina',
                'forma_farmaceutica' => 'Tableta',
                'presentacion' => 'Caja x 10',
                'concentracion' => '10mg',
                'accion_terapeutica' => 'Antihistamínico',
                'unidad_medida' => 'mg',
                'usa_receta' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categoria_id' => 2,
                'laboratorio_id' => 2,
                'codigo_producto' => 'PROD005',
                'codigo_barra' => '123456789005',
                'nombre_comercial' => 'Omeprazol 20mg',
                'nombre_generico' => 'Omeprazol',
                'forma_farmaceutica' => 'Cápsula',
                'presentacion' => 'Caja x 14',
                'concentracion' => '20mg',
                'accion_terapeutica' => 'Antiulceroso',
                'unidad_medida' => 'mg',
                'usa_receta' => true,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categoria_id' => 1,
                'laboratorio_id' => 1,
                'codigo_producto' => 'PROD006',
                'codigo_barra' => '123456789006',
                'nombre_comercial' => 'Metformina 850mg',
                'nombre_generico' => 'Metformina',
                'forma_farmaceutica' => 'Tableta',
                'presentacion' => 'Caja x 30',
                'concentracion' => '850mg',
                'accion_terapeutica' => 'Antidiabético',
                'unidad_medida' => 'mg',
                'usa_receta' => true,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categoria_id' => 3,
                'laboratorio_id' => 3,
                'codigo_producto' => 'PROD007',
                'codigo_barra' => '123456789007',
                'nombre_comercial' => 'Salbutamol 100mcg',
                'nombre_generico' => 'Salbutamol',
                'forma_farmaceutica' => 'Inhalador',
                'presentacion' => 'Inhalador x 200 dosis',
                'concentracion' => '100mcg',
                'accion_terapeutica' => 'Broncodilatador',
                'unidad_medida' => 'mcg',
                'usa_receta' => true,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categoria_id' => 2,
                'laboratorio_id' => 2,
                'codigo_producto' => 'PROD008',
                'codigo_barra' => '123456789008',
                'nombre_comercial' => 'Cetirizina 10mg',
                'nombre_generico' => 'Cetirizina',
                'forma_farmaceutica' => 'Tableta',
                'presentacion' => 'Caja x 20',
                'concentracion' => '10mg',
                'accion_terapeutica' => 'Antihistamínico',
                'unidad_medida' => 'mg',
                'usa_receta' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categoria_id' => 1,
                'laboratorio_id' => 1,
                'codigo_producto' => 'PROD009',
                'codigo_barra' => '123456789009',
                'nombre_comercial' => 'Aspirina 100mg',
                'nombre_generico' => 'Ácido acetilsalicílico',
                'forma_farmaceutica' => 'Tableta',
                'presentacion' => 'Caja x 30',
                'concentracion' => '100mg',
                'accion_terapeutica' => 'Antiplaquetario',
                'unidad_medida' => 'mg',
                'usa_receta' => false,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'categoria_id' => 3,
                'laboratorio_id' => 3,
                'codigo_producto' => 'PROD010',
                'codigo_barra' => '123456789010',
                'nombre_comercial' => 'Ranitidina 150mg',
                'nombre_generico' => 'Ranitidina',
                'forma_farmaceutica' => 'Tableta',
                'presentacion' => 'Caja x 20',
                'concentracion' => '150mg',
                'accion_terapeutica' => 'Antiulceroso',
                'unidad_medida' => 'mg',
                'usa_receta' => true,
                'imagen' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
